# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wiz-fr-cluster
  region: us-east-1

vpc:
  id: "vpc-068f6d161b2b8eea0"  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    private:
      us-east-1a:
        id: "subnet-05fd28767c17f5cfb"  # Replace with your private subnet ID in us-east-1a
        cidr: "192.168.128.0/18" # (optional, must match CIDR used by the given subnet)
      us-east-1b:
        id: "subnet-0f6e1c2aa7233d130"  # Replace with your private subnet ID in us-east-1b
        cidr: "192.168.192.0/18" # (optional, must match CIDR used by the given subnet)
    public:
      us-east-1a:
        id: "subnet-018901167754cf17a"  # Replace with your public subnet ID
        cidr: "192.168.0.0/18" # (optional, must match CIDR used by the given subnet)
      us-east-1b:
        id: "subnet-04fc8d2346ebe3762"  # Replace with your public subnet ID
        cidr: "192.168.64.0/18" # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: wiz-fr-node-group
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled